### ISSUE TITLE
Add support for other taxonomic classifiers

### ISSUE THREAD

**Issue by hjarnek** [liberjul/CONSTAXv2#14]
Hello,

Interesting tool, this Constax! I really like the idea. However, there are other taxonomic classifiers out there which are highly relevant. How are the outlooks on implementing support for other classifiers too, such as i.e. SPINGO or Sklearn?

**Comment by liberjul** [comment]
Hi @hjarnek ,

Thanks for the suggestion! I have tested other classifiers, and could reasonably try to write wrappers. A couple points:
1) The classifiers chosen are the ones which gave the best performance in testing: [figure](https://github.com/liberjul/CONSTAXv2_ms_code/blob/master/figures/Fig_1.pdf) and [manuscript](https://academic.oup.com/bioinformatics/article/37/21/3941/6271412)
2) I would likely make these as plugins to avoid headaches during default installation.
3) I'm a busy PhD student trying to get my primary work done, so I'll do my best to work on improvements when I can!

Thank you,
Julian
