### ISSUE TITLE
RDP Classifier consistently encounters java.lang.OutOfMemoryError with Eukaryotes

### ISSUE THREAD

**Issue by szymanskishay** [liberjul/CONSTAXv2#9]
I am attempting to assign taxonomy to Eukaryotes and repeatedly encounter an error with memory allotment, from what I can tell at least. I think it might be related to needing to use the duplicate taxon name fix but I am unsure. 
Slight sidebar, but I do really appreciate that this has built in a way to deal with the duplicate taxa problem.
I have already tried going to my CTAX2 environment to change the default for -Xmx to allow more memory (from 1GB to 2GB), but a source I found online seemed to suggest that it couldnt go past 2GB very well, so I am hesitant to alter it further. 
-------------------------------
Relevant excerpt from the slurm below.
-------------------------------
Training RDP Classifier
java -Xmx -jar /mnt/research/rdp/public/RDPTools/classifier.jar train -o /mnt/home/shemans6/Cecilia/db///. -s /mnt/home/shemans6/Cecilia/db///sh_general_release_dynamic_all_29.11.2022_dev__RDP_trained.fasta -t /mnt/home/shemans6/Cecilia/db///sh_general_release_dynamic_all_29.11.2022_dev__RDP_taxonomy_trained.txt > rdp_train.out 2>&1
edu.msu.cme.rdp.classifier.train.NameRankDupException: Error: duplicate taxon name and rank in the taxonomy file.
crambe	genus	2
opercularia	genus	2
phialina	genus	2
gomphus	genus	2
cynodon	genus	2
mertensia	genus	2
stokesia	genus	2
globodera	genus	2
alaria	genus	2
chondrilla	genus	2
rhytisma	genus	2
siphonaria	genus	2

	at edu.msu.cme.rdp.classifier.train.TreeFactory.creatTaxidMap(TreeFactory.java:126)
	at edu.msu.cme.rdp.classifier.train.TreeFactory.<init>(TreeFactory.java:61)
	at edu.msu.cme.rdp.classifier.train.ClassifierTraineeMaker.<init>(ClassifierTraineeMaker.java:63)
	at edu.msu.cme.rdp.classifier.train.ClassifierTraineeMaker.main(ClassifierTraineeMaker.java:170)
	at edu.msu.cme.rdp.classifier.cli.ClassifierMain.main(ClassifierMain.java:77)
RDP training error, redoing with duplicate taxa
python /mnt/home/shemans6/anaconda3/envs/CTAX2/opt/constax-2.0.18-0/FormatRefDB.py -d /mnt/home/shemans6/Cecilia/db/sh_general_release_dynamic_all_29.11.2022_dev.fasta -t /mnt/home/shemans6/Cecilia/db// -f UNITE -p /mnt/home/shemans6/anaconda3/envs/CTAX2/opt/constax-2.0.18-0 --dup
Importing subscripts from /mnt/home/shemans6/anaconda3/envs/CTAX2/opt/constax-2.0.18-0

____________________________________________________________________
Reformatting database

UNITE format detected

Reference database FASTAs formatted in 2.699999325 seconds...

	Training Taxonomy

	Duplicate taxa being handled with numerical suffices

	Adding Full Lineage

Database formatting complete
____________________________________________________________________

java -Xmx -jar /mnt/research/rdp/public/RDPTools/classifier.jar train -o /mnt/home/shemans6/Cecilia/db///. -s /mnt/home/shemans6/Cecilia/db///sh_general_release_dynamic_all_29.11.2022_dev__RDP_trained.fasta -t /mnt/home/shemans6/Cecilia/db///sh_general_release_dynamic_all_29.11.2022_dev__RDP_taxonomy_trained.txt > rdp_train.out 2>&1
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.msu.cme.rdp.classifier.train.RawHierarchyTree.initWordOccurrence(RawHierarchyTree.java:124)
	at edu.msu.cme.rdp.classifier.train.TreeFactory.addSequencewithLineage(TreeFactory.java:273)
	at edu.msu.cme.rdp.classifier.train.TreeFactory.parseSequenceFile(TreeFactory.java:152)
	at edu.msu.cme.rdp.classifier.train.ClassifierTraineeMaker.<init>(ClassifierTraineeMaker.java:65)
	at edu.msu.cme.rdp.classifier.train.ClassifierTraineeMaker.main(ClassifierTraineeMaker.java:170)
	at edu.msu.cme.rdp.classifier.cli.ClassifierMain.main(ClassifierMain.java:77)
Command 'bash -c '/mnt/home/shemans6/anaconda3/envs/CTAX2/opt/constax-2.0.18-0/constax_no_inputs.sh'' returned non-zero exit status 1.
------------------------------------------------------------------------------------------------
When rdp_train.out gets written, it is just "Exception in thread "main"..." and the things indented under it.
What is more curious is that it still makes RDP relevant files (ie: sh_general_release....RDP_taxonomy.txt, ..._RDP_taxonomy_headers.txt, ..._RDP_taxonomy_trained.txt, ..._RDP_trained.fasta)
It seems to not make "training_check.txt", which causes a failure slightly further down (below)
--------------
CONSTAX2: Improved taxonomic classification of environmental DNA markers
Julian Aaron Liber, Gregory Bonito, Gian Maria Niccolò Benucci
Bioinformatics, Volume 37, Issue 21, 1 November 2021, Pages 3941–3943; doi: https://doi.org/10.1093/bioinformatics/btab347
Cannot classify without existing training files, please specify -t
Command 'bash -c '/mnt/home/shemans6/anaconda3/envs/CTAX2/opt/constax-2.0.18-0/constax_no_inputs.sh'' returned non-zero exit status 1.
grep: /mnt/home/shemans6/Cecilia/db///training_check.txt: No such file or directory
-------------
I am trying some fixes out currently but would love to hear anything that could help regardless.

Additional info: I am using the UNITE general eukaryotic data base release "[sh_general_release_dynamic_all_29.11.2022_dev.fasta](https://doi.plutof.ut.ee/doi/10.15156/BIO/2483913)". I am using this on the MSU HPCC as well.

**Comment by Gian77** [comment]
Hello @szymanskishay,

can you tell me how much RAM are you using in the `SLURM` job you are submitting?
You can copy an dpaste your job script here to better debug.
Thanks,
G.

**Comment by szymanskishay** [comment]
> Please give this a try
> 
> ```
> #SBATCH --cpus-per-task=32
> #SBATCH --mem=128G
> ```

This appears to have worked! Thank you!

**Comment by Gian77** [comment]
Hello @szymanskishay,

yes, you sould use a different file for the `--isolates`. Maybe you have some ITS sequences of the contaminanst present in the lab where the library was prepared? Or you can use culture isolates sequences (that is the original purpose of it). 

I am working on a solution for your problem, will come up soon with a new fix of this https://github.com/Gian77/Cecilia soon.

Thanks,
Gian

**Comment by liberjul** [comment]
Thanks for your quetion @szymanskishay, and thanks for addressing it @Gian77. It seems like we've resolved the issue, so I'm closing.
